on:
  pull_request:
    types: [opened, synchronize]
    
jobs:
  ESLint-evaluator:
    runs-on: self-hosted
    name: ESLint
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout

      - name: Fetch ESLint evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/eslint-linter-action
          ref: v3
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/eslint-evaluator
          
      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '14'
          
      - name: Restore protected files
        uses: ./.github/actions/blocked-files-checkout
        with:
          restore_branch: 'master'
          
      - name: Run ESLint evaluator
        uses: ./.github/actions/eslint-evaluator
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}

  Evaluator:
    runs-on: self-hosted
    name: Evaluator
    needs: [ESLint-evaluator]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 'password'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:    
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout

      - name: Fetch Jest evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/jest-evaluator-action
          ref: v9.2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/jest-evaluator

      - name: Fetch Store evaluation
        uses: actions/checkout@v2
        with:
          repository: betrybe/store-evaluation-action
          ref: v4.2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/store-evaluation

      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '12'

      - name: Restore protected files
        uses: ./.github/actions/blocked-files-checkout
        with:
          restore_branch: 'master'

      - name: Run Jest evaluation
        id: evaluator
        uses: ./.github/actions/jest-evaluator
        with:
          pr_author_username: ${{ github.event.pull_request.user.login }}
        env:
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: 'password'
          HOSTNAME: 'mysql'

      - name: Run Store evaluation
        uses: ./.github/actions/store-evaluation
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: production
          pr-number: ${{ github.event.pull_request.number }}
